<a href="https://colab.research.google.com/github/ShreshthaJha6/MachineLearning/blob/main/session3_ShreshthaJhsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''learn and  implement-
Linear SVC
SGD Classifier
MLP classifier
Perceptron
Logistic regression(classification)
Logistic regressionCV
SVC
CallibratedClassifierCV'''
#will be perfroming on iris dataset
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#DATASET
iris= datasets.load_iris()
df= pd.DataFrame(iris.data, columns= iris.feature_names)
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
df.shape

(150, 4)

In [ ]:
df['label']= iris.target
df.shape

(150, 5)

In [ ]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
label                0
dtype: int64

In [ ]:
df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [ ]:
#splitting the dataset
x= iris.data #or df.drop(columns='label',axis=1)
y= iris.target #or df['label']

In [ ]:
x_train, x_test, y_train, y_test= train_test_split( x, y, test_size=0.2)

to learn about any model search: model_name sklearn

# Linear SVC

# SGD Classifier

# Perceptron

In [ ]:
from sklearn.linear_model import Perceptron

In [ ]:
modelP= Perceptron()
parameters={
    'penalty':['l1','l2','elasticnet']
}

In [ ]:
#GRID SEARCH
classifier= GridSearchCV(modelP, parameters, cv=5)
classifier.fit(x,y)

GridSearchCV(cv=5, estimator=Perceptron(),
             param_grid={'penalty': ['l1', 'l2', 'elasticnet']})

In [ ]:
classifier.cv_results_
best_param= classifier.best_params_
print(best_param)

{'penalty': 'elasticnet'}


In [ ]:
result= pd.DataFrame(classifier.cv_results_)
result

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       0.005117      0.002160         0.001085        0.000498            l1   
1       0.003503      0.000076         0.000838        0.000051            l2   
2       0.003752      0.000192         0.000771        0.000029    elasticnet   

                      params  split0_test_score  split1_test_score  \
0          {'penalty': 'l1'}           0.533333           0.700000   
1          {'penalty': 'l2'}           0.900000           0.700000   
2  {'penalty': 'elasticnet'}           0.866667           0.866667   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           0.766667           0.766667           0.900000         0.733333   
1           0.666667           0.666667           0.666667         0.720000   
2           0.666667           0.866667           0.700000         0.793333   

   std_test_score  rank_test_score  
0        0.119257                2  
1        0.090921                3  
2        0.090431                1

In [ ]:
result=result[['param_penalty','mean_test_score']]
result

param_penalty  mean_test_score
0            l1         0.733333
1            l2         0.720000
2    elasticnet         0.793333

In [ ]:
print("highest accuracy score: ", round(classifier.best_score_*100,2)," %")
print("best parameter: ",classifier.best_params_)

highest accuracy score:  79.33  %
best parameter:  {'penalty': 'elasticnet'}


In [ ]:
#RANDOMIZED SEARCH
classifier= RandomizedSearchCV(modelP, parameters, cv=5)
classifier.fit(x,y)

RandomizedSearchCV(cv=5, estimator=Perceptron(),
                   param_distributions={'penalty': ['l1', 'l2', 'elasticnet']})

In [ ]:
classifier.cv_results_
print(classifier.cv_results_)

{'mean_fit_time': array([0.00710521, 0.00392995, 0.00482793]), 'std_fit_time': array([2.55030372e-03, 9.73602462e-05, 1.36328787e-03]), 'mean_score_time': array([0.00199728, 0.00091095, 0.00092859]), 'std_score_time': array([2.02029212e-03, 2.90883955e-05, 1.84705321e-05]), 'param_penalty': masked_array(data=['l1', 'l2', 'elasticnet'],
             mask=[False, False, False],
       fill_value='?',
            dtype=object), 'params': [{'penalty': 'l1'}, {'penalty': 'l2'}, {'penalty': 'elasticnet'}], 'split0_test_score': array([0.53333333, 0.9       , 0.86666667]), 'split1_test_score': array([0.7       , 0.7       , 0.86666667]), 'split2_test_score': array([0.76666667, 0.66666667, 0.66666667]), 'split3_test_score': array([0.76666667, 0.66666667, 0.86666667]), 'split4_test_score': array([0.9       , 0.66666667, 0.7       ]), 'mean_test_score': array([0.73333333, 0.72      , 0.79333333]), 'std_test_score': array([0.11925696, 0.09092121, 0.09043107]), 'rank_test_score': array([2, 3, 1], d

In [ ]:
result=pd.DataFrame(classifier.cv_results_)
result=result[['param_penalty','mean_test_score']]
result

param_penalty  mean_test_score
0            l1         0.733333
1            l2         0.720000
2    elasticnet         0.793333

In [ ]:
#RANDOMIZED SEARCH
print("highest accuracy score: ", round(classifier.best_score_*100,2)," %")
print("best parameters: ", classifier.best_params_)

highest accuracy score:  79.33  %
best parameters:  {'penalty': 'elasticnet'}


In [ ]:
#TRAINING
modelP= Perceptron(penalty='elasticnet')
modelP.fit(x_train,y_train)

Perceptron(penalty='elasticnet')

In [ ]:
print('score: ',round(modelP.score(x_train,y_train)*100,2)," %")

score:  69.17  %


In [ ]:
#TESTING
y_pred= modelP.predict(x_test)

In [ ]:
cfm= confusion_matrix(y_test,y_pred)
print(cfm)
cfr= classification_report(y_test, y_pred)
print(cfr)

[[ 8  0  0]
 [ 0  0 13]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.00      0.00      0.00        13
           2       0.41      1.00      0.58         9

    accuracy                           0.57        30
   macro avg       0.47      0.67      0.53        30
weighted avg       0.39      0.57      0.44        30



# MLP Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
model2= MLPClassifier()

In [ ]:
parameters= {
    'activation':['identity','logistic','tanh','relu'],
    'solver':['lbfgs','sgd','adam']
}

In [ ]:
#GRID SEARCH
clf= GridSearchCV(model2,parameters,cv =5)
clf.fit(x,y)

GridSearchCV(cv=5, estimator=MLPClassifier(),
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'solver': ['lbfgs', 'sgd', 'adam']})

In [ ]:
clf.cv_results_
best_parameter= clf.best_params_
print(best_parameter)

{'activation': 'tanh', 'solver': 'adam'}


In [ ]:
result= pd.DataFrame(clf.cv_results_)

In [ ]:
result_gridSearch= result[['param_activation','param_solver','mean_test_score']]
result_gridSearch

param_activation param_solver  mean_test_score
0          identity        lbfgs         0.973333
1          identity          sgd         0.960000
2          identity         adam         0.973333
3          logistic        lbfgs         0.966667
4          logistic          sgd         0.713333
5          logistic         adam         0.946667
6              tanh        lbfgs         0.973333
7              tanh          sgd         0.966667
8              tanh         adam         0.986667
9              relu        lbfgs         0.960000
10             relu          sgd         0.953333
11             relu         adam         0.966667

In [ ]:
#highest score: 98.67%
# best param= {'activation':'relu','solver':'lbfgs'}

In [ ]:
# RANDOMIZED SEARCH
clf= RandomizedSearchCV(model2,parameters,cv=5)
clf.fit(x,y)

RandomizedSearchCV(cv=5, estimator=MLPClassifier(),
                   param_distributions={'activation': ['identity', 'logistic',
                                                       'tanh', 'relu'],
                                        'solver': ['lbfgs', 'sgd', 'adam']})

In [ ]:
clf.cv_results_
best_parameter= clf.best_params_
print(best_parameter)

{'solver': 'adam', 'activation': 'identity'}


In [ ]:
result= pd.DataFrame(clf.cv_results_)
best_randomizedsearch= result[['param_solver','param_activation','mean_test_score']]

In [ ]:
print(best_randomizedsearch)

  param_solver param_activation  mean_test_score
0          sgd             tanh         0.966667
1          sgd         identity         0.973333
2        lbfgs             relu         0.953333
3        lbfgs             tanh         0.966667
4          sgd         logistic         0.693333
5          sgd             relu         0.940000
6        lbfgs         logistic         0.973333
7        lbfgs         identity         0.960000
8         adam         identity         0.980000
9         adam         logistic         0.960000


In [ ]:
#highest accuracy: 97.33%
#best params= {'activation':'relu','solver':'adam'}

In [ ]:
#model TRAINING
model2= MLPClassifier(activation='relu',solver='lbfgs')
model2.fit(x_train,y_train)

MLPClassifier(solver='lbfgs')

In [ ]:
print("Score: ",model2.score(x_train,y_train))

Score:  1.0


In [ ]:
#model TESTING
y_pred=model2.predict(x_test)
cfm= confusion_matrix(y_test,y_pred)
print(cfm)
cfr= classification_report(y_test,y_pred)
print(cfr)

[[ 8  0  0]
 [ 0 12  1]
 [ 0  1  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.92      0.92      0.92        13
           2       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30

